config/routes.rb
AdminSide::Application.routes.draw do
  namespace :cms do
    root to: "dashboard#index"
    resources :dashboard, only: [:index]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cms/base_controller.rb
class Cms::BaseController < ApplicationController
  respond_to :html, :json
  layout "cms/cms"

  before_filter :default_attributes 
  before_filter :sanitize_model_name


  inherit_resources
  # has_scope :page,     default:  1

  # has_scope :q do |controller, scope|
  #   scope.search(controller.params[:q] || "")
  # end


  def create
    create!(:notice => "#{@instance_name.humanize} succesfully created" ) {send("cms_#{@collection_name}_path")}
  end
  

  def update
    update!(:notice => "#{@instance_name.humanize} succesfully updated" ) { send("edit_cms_#{@instance_name}_path", params[:id]) }
  end

  def destroy
    destroy!(:notice => "#{@instance_name.humanize} succesfully removed" ) { send("cms_#{@collection_name}_path") }
  end


  private
  
    def sanitize_model_name
      if @model
        @collection_name = @model.name.underscore.gsub("/","_").downcase.pluralize
        @instance_name = @model.name.underscore.gsub("/","_").downcase
      end
    end
    
    def attributes_types_from(model)
      attributes = []
      if @model.try(:columns_hash)
        @model.columns_hash.each do |k,v| 
          attributes.tap do |attr|
            
            if k == 'body'
              
              attr << {name: k, type: v.type, class: 'redactor', as: :text}
            else
              attr << {name: k, type: v.type}
            end
          end
        end
        return attributes
      end
    end

    def default_attributes
      @model = resource_class
      @attributes_hash = attributes_types_from @model
    end
end

app/controllers/cms/dashboard_controller.rb
class Cms::DashboardController < Cms::BaseController 
  
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cms/dashboard/index.html.haml
h1 "Dashboard"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdminSide</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/cms/cms.html.haml
!!!
%html
  %head
    %title
      Beatgonza
    = stylesheet_link_tag  "cms"
    = javascript_include_tag "cms"
    = csrf_meta_tags

  %body#nf_bootstrap
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container-fluid
          = link_to "Admin", cms_root_path, class: "brand"
          .navbar-content
            %ul.nav
              %li#dashboard.current
                %a{:href => "/cms"} Dashboard
              %li#admin.dropdown
                %a{:href => "#", class: "dropdown-toggle", :'data-toggle' => "dropdown"} Admin
                %ul.dropdown-menu
                  / %li
                  /   %a{:href => cms_pages_path} Pages    
              
    .main_container

      .container-fluid
        = yield :breadcrumbs

        - if flash[:notice]
          .alert.alert-success= flash[:notice] 
        - if flash[:error]
          .alert.alert-error= flash[:error] 
        = yield